spring:
    profile: dev
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        username: writeuser
        password: "write@520"
        url: jdbc:mysql://192.168.20.88:3306/wirelessapi?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    jpa:
        database: MYSQL
        generate-ddl: true
        show-sql: true
        hibernate: 
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
push: 
    spConfig: 
        message: dev-sp
        maxCount: 123
        isEnv: true
    alConfig:
        message: dev-al
        maxCount: 890
        isEnv: false


        